#!/bin/bash 
rm -rf optci_example_matrix
git clone https://github.com/realincubus/optci_example_matrix.git

mkdir -p artifacts/example_hooks/001_configure
echo 'export CHECKOUT_FOLDER=optci_example_matrix' > artifacts/example_hooks/001_configure/test
