#!/bin/bash
OPTCI_PREPARE

COMMAND="./bin_matrix_multiply_example $SIZE $ITERATIONS > /dev/null"

time="$(OPTCI_PIN_RUN "$COMMAND")"

CONFIG_TUPLE=$OPTCI_CONFIG_TUPLE

echo "export CHANGED_RUNTIME_$CONFIG_TUPLE=$time" > $ARTIFACT/changed_runtime_$CONFIG_TUPLE

OPTCI_CLEANUP
