#!/bin/bash

echo "change the code here"

ln -fs  perf.data.base perf.data
perf annotate --stdio -l -P -d bin_matrix_multiply_example > perf.base.txt

echo "convert the perf data to hotspots.txt"
# TODO no absolute path
/root/optci/bin_perf_data_converter perf.base.txt

# TODO this needs to be infered somehow
PLUGIN_PATH=/root/ClanPlugin/lib/ClanPlugin.so 
export PATH=$HOME/install/bin/:$PATH
export LD_LIBRARY_PATH=/root/pet_install/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/root/pluto_install/lib:$LD_LIBRARY_PATH

ldd -v $PLUGIN_PATH > ldd.res

FIXIT_COMPILER=clang
FIXIT_COMPILER_FLAGS="-std=c++14 -g -fsyntax-only"
PLUGIN_FLAGS="$FIXIT_COMPILER_FLAGS -Xclang -load -Xclang $PLUGIN_PATH -Xclang -add-plugin -Xclang clan -Xclang -plugin-arg-clan -Xclang -profiling-data -Xclang -plugin-arg-clan -Xclang hotspots.out -Xclang -plugin-arg-clan -Xclang"

OMP_FIXER_FLAGS="$PLUGIN_FLAGS -emit-openmp"
FIXIT_FLAGS="-Xclang -fixit=opt"

SOURCE=main.cpp

OMP_FIXIT_COMMAND="$FIXIT_COMPILER $OMP_FIXER_FLAGS $FIXIT_COMPILER_FLAGS $FIXIT_FLAGS -c $SOURCE"

echo running $OMP_FIXIT_COMMAND 

$OMP_FIXIT_COMMAND &> plugin.out

if [[ $? -ne 0 ]]; then
  echo "error optimizing main.cpp"
fi

# TODO right now it creates main.opt.cpp. change to directly overwrite the original
mv main.cpp main.orignal.cpp
mv main.opt.cpp main.cpp

