- scaling_phases: [ "config/phases/002_all" ]
  matrix:
    - name: "EMIT_TYPE"
      values: [ "-emit-hpx", "-emit-tbb", "-emit-openmp", "-emit-cilk", "-emit-openacc", "no-change" ]
- scaling_phases: [ "config/phases/002_all/005_run" ]
  matrix: auto_pow2
