- scaling_phases: [ "config/phases/002_all" ]
  matrix:
    - name: "EMIT_TYPE"
      values: [ "-emit-openmp", "-emit-cilk", "-emit-openacc" ]
- scaling_phases: [ "config/phases/002_all/004_base/001_run", "config/phases/002_all/007_rerun/001_run" ]
  matrix: auto_pow2
