#!/bin/bash

# compare the content of the env vars
echo comparing runtime of two codes

IS_SPEEDUP=$(echo "$CHANGED_RUNTIME < $BASE_RUNTIME" | bc -l)
if [[ $IS_SPEEDUP == "1"  ]]; then
  SPEEDUP=$(echo "$BASE_RUNTIME / $CHANGED_RUNTIME" | bc -l)
  echo "optimization caused a speedup of $SPEEDUP"
fi
