#!/bin/bash -xe


if [[ $EMIT_TYPE == "no-change" ]]; then
  cmake .
fi

if [[ $EMIT_TYPE == "-emit-openmp" ]]; then
  cmake -DCMAKE_CXX_FLAGS="-fopenmp" .
fi

if [[ $EMIT_TYPE == "-emit-openacc" ]]; then
  cmake -DCMAKE_CXX_FLAGS="-fopenacc" .
fi

if [[ $EMIT_TYPE == "-emit-cilk" ]]; then
  cmake -DCMAKE_CXX_FLAGS="-fcilkplus" .
fi

if [[ $EMIT_TYPE == "-emit-tbb" ]]; then
  cmake -DCMAKE_CXX_STANDARD_LIBRARIES="-ltbb" .
fi

if [[ $EMIT_TYPE == "-emit-hpx" ]]; then
  cmake -DCMAKE_CXX_STANDARD_LIBRARIES="-lhpx /usr/local/lib/libhpx_init.a -lboost_chrono -lboost_date_time -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lboost_context -lboost_random -lboost_atomic" .
fi
