#!/bin/bash

if [[ $EMIT_TYPE == "-emit-openmp" ]]; then
  cmake -DCMAKE_CXX_FLAGS="-fopenmp" .
fi

if [[ $EMIT_TYPE == "-emit-cilk" ]]; then
  cmake -DCMAKE_CXX_FLAGS="-fcilkplus" .
fi

if [[ $EMIT_TYPE == "-emit-acc" ]]; then
  cmake -DCMAKE_CXX_FLAGS="-fopenacc" .
fi

make -j 
