#!/bin/bash
OPTCI_PREPARE

COMMAND="./bin_matrix_multiply_example $SIZE $ITERATIONS"

echo running $COMMAND
echo $PWD

time="$(OPTCI_PIN_RUN $COMMAND)"

CONFIG_TUPLE=$OPTCI_CONFIG_TUPLE
echo "config tuple: $CONFIG_TUPLE"

#echo "export BASE_RUNTIME_$CONFIG_TUPLE=$time" > $ARTIFACT/base_runtime_$CONFIG_TUPLE

echo BASE_RUNTIME_$CONFIG_TUPLE=$time >> $RESULT_FILE


OPTCI_CLEANUP
