#!/bin/bash
OPTCI_PREPARE

time="$(OPTCI_RUN perf record -F 99 -g ./bin_matrix_multiply_example $SIZE $ITERATIONS)"

echo "export BASE_RUNTIME=$time" > $ARTIFACT/base_runtime

mv perf.data perf.data.base

OPTCI_CLEANUP
